WSBundle\Entity\Subscriber:
    type: entity
    table: null
    repositoryClass: WSBundle\Repository\SubscriberRepository
    id:
        id:
            type: integer
            id: true
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        telephone:
            type: string
            length: 255
    lifecycleCallbacks: {  }
